# Generated by Django 5.2.4 on 2025-08-03 06:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTokenSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_users', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=0)),
                ('total_input_tokens', models.IntegerField(default=0)),
                ('total_output_tokens', models.IntegerField(default=0)),
                ('total_cost_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_cost_bdt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Daily Token Summary',
                'verbose_name_plural': 'Daily Token Summaries',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TokenCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50, unique=True)),
                ('input_price_per_million', models.DecimalField(decimal_places=6, max_digits=10)),
                ('output_price_per_million', models.DecimalField(decimal_places=6, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Token Cost',
                'verbose_name_plural': 'Token Costs',
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], default='free', max_length=20)),
                ('monthly_token_limit', models.IntegerField(default=10000)),
                ('monthly_cost_bdt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('current_month_tokens_used', models.IntegerField(default=0)),
                ('reset_date', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Subscription',
                'verbose_name_plural': 'User Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='UserTokenUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('dataset_name', models.CharField(blank=True, max_length=255, null=True)),
                ('question', models.TextField()),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('model_used', models.CharField(default='gemini-2.5-flash-lite', max_length=50)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('cost_bdt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=122.5, max_digits=10)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Token Usage',
                'verbose_name_plural': 'User Token Usages',
                'ordering': ['-timestamp'],
            },
        ),
    ]
